//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized By:.
        /// </summary>
        internal static string AdjustmentVoucher_AuthorizedBy {
            get {
                return ResourceManager.GetString("AdjustmentVoucher_AuthorizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;Back to Issue Adjustment Voucher.
        /// </summary>
        internal static string AdjustmentVoucher_BackLink {
            get {
                return ResourceManager.GetString("AdjustmentVoucher_BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By:.
        /// </summary>
        internal static string AdjustmentVoucher_By {
            get {
                return ResourceManager.GetString("AdjustmentVoucher_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Issued:.
        /// </summary>
        internal static string AdjustmentVoucher_IssueDate {
            get {
                return ResourceManager.GetString("AdjustmentVoucher_IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Voucher.
        /// </summary>
        internal static string AdjustmentVoucher_Title {
            get {
                return ResourceManager.GetString("AdjustmentVoucher_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher#:.
        /// </summary>
        internal static string AdjustmentVoucher_Voucher {
            get {
                return ResourceManager.GetString("AdjustmentVoucher_Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationery Store Inventory System.
        /// </summary>
        internal static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string ApproveButton_text {
            get {
                return ResourceManager.GetString("ApproveButton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Requisition.
        /// </summary>
        internal static string ApproveRequisition_Title {
            get {
                return ResourceManager.GetString("ApproveRequisition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Department Representative.
        /// </summary>
        internal static string AssignDeptRespresentative_Title {
            get {
                return ResourceManager.GetString("AssignDeptRespresentative_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Temporary Department Head.
        /// </summary>
        internal static string AssignTempDeptHead_Title {
            get {
                return ResourceManager.GetString("AssignTempDeptHead_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Temporary Department Representative.
        /// </summary>
        internal static string AssignTempDeptRep_Title {
            get {
                return ResourceManager.GetString("AssignTempDeptRep_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department List.
        /// </summary>
        internal static string BlackListDepartment_DepartmentList {
            get {
                return ResourceManager.GetString("BlackListDepartment_DepartmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black List Department.
        /// </summary>
        internal static string BlackListDepartment_Title {
            get {
                return ResourceManager.GetString("BlackListDepartment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password :.
        /// </summary>
        internal static string ChangePassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password :.
        /// </summary>
        internal static string ChangePassword_NewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password :.
        /// </summary>
        internal static string ChangePassword_OldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        internal static string ChangePassword_text {
            get {
                return ResourceManager.GetString("ChangePassword_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Requisition.
        /// </summary>
        internal static string CheckRequisition_header_Text {
            get {
                return ResourceManager.GetString("CheckRequisition_header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        internal static string CheckRequisition_Status_Label {
            get {
                return ResourceManager.GetString("CheckRequisition_Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string CreateDiscrepencyReport_AddButton {
            get {
                return ResourceManager.GetString("CreateDiscrepencyReport_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Voucher Form.
        /// </summary>
        internal static string CreateDiscrepencyReport_GropuBoxHeader {
            get {
                return ResourceManager.GetString("CreateDiscrepencyReport_GropuBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Discrepency Report.
        /// </summary>
        internal static string CreateDiscrepencyReport_Header {
            get {
                return ResourceManager.GetString("CreateDiscrepencyReport_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No :.
        /// </summary>
        internal static string CreateDiscrepencyReport_ItemNo {
            get {
                return ResourceManager.GetString("CreateDiscrepencyReport_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price :.
        /// </summary>
        internal static string CreateDiscrepencyReport_ItemPrice {
            get {
                return ResourceManager.GetString("CreateDiscrepencyReport_ItemPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity :.
        /// </summary>
        internal static string CreateDiscrepencyReport_Quantity {
            get {
                return ResourceManager.GetString("CreateDiscrepencyReport_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason :.
        /// </summary>
        internal static string CreateDiscrepencyReport_Reason {
            get {
                return ResourceManager.GetString("CreateDiscrepencyReport_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attn:.
        /// </summary>
        internal static string CreatePurchaseOrder_Attention {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver To:.
        /// </summary>
        internal static string CreatePurchaseOrder_DeliverTo {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder_DeliverTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string CreatePurchaseOrder_Description {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No:.
        /// </summary>
        internal static string CreatePurchaseOrder_ItemNumber {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder_ItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Number:.
        /// </summary>
        internal static string CreatePurchaseOrder_PONo {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder_PONo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string CreatePurchaseOrder_Price {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string CreatePurchaseOrder_Quantity {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier:.
        /// </summary>
        internal static string CreatePurchaseOrder_Supplier {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply the following items by:.
        /// </summary>
        internal static string CreatePurchaseOrder_SupplyDate {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder_SupplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Purchase Order.
        /// </summary>
        internal static string CreatePurchaseOrder_Titile {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder_Titile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Qty : .
        /// </summary>
        internal static string CreateStationeryRetreivalList_ActualQtyText {
            get {
                return ResourceManager.GetString("CreateStationeryRetreivalList_ActualQtyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin :.
        /// </summary>
        internal static string CreateStationeryRetreivalList_BinText {
            get {
                return ResourceManager.GetString("CreateStationeryRetreivalList_BinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set based on Request Sequence.
        /// </summary>
        internal static string CreateStationeryRetreivalList_ButtonText {
            get {
                return ResourceManager.GetString("CreateStationeryRetreivalList_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show automatically fulfilled Items.
        /// </summary>
        internal static string CreateStationeryRetreivalList_HyperlinkText {
            get {
                return ResourceManager.GetString("CreateStationeryRetreivalList_HyperlinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed Qty :.
        /// </summary>
        internal static string CreateStationeryRetreivalList_NeededQtyText {
            get {
                return ResourceManager.GetString("CreateStationeryRetreivalList_NeededQtyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval No. :.
        /// </summary>
        internal static string CreateStationeryRetreivalList_RetrievalNo {
            get {
                return ResourceManager.GetString("CreateStationeryRetreivalList_RetrievalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Stationery Retrieval List.
        /// </summary>
        internal static string CreateStationeryRetrievalList_Title {
            get {
                return ResourceManager.GetString("CreateStationeryRetrievalList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Authorized Person.
        /// </summary>
        internal static string CurrentAuthorizedPerson {
            get {
                return ResourceManager.GetString("CurrentAuthorizedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton_text {
            get {
                return ResourceManager.GetString("DeleteButton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email address:.
        /// </summary>
        internal static string ForgotPassword_Email {
            get {
                return ResourceManager.GetString("ForgotPassword_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email Address.
        /// </summary>
        internal static string ForgotPassword_grouptext {
            get {
                return ResourceManager.GetString("ForgotPassword_grouptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Disbursement.
        /// </summary>
        internal static string GenerateDisbursement_Title {
            get {
                return ResourceManager.GetString("GenerateDisbursement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized By:.
        /// </summary>
        internal static string IssueAdjustmentVoucher_AuthorizedBy {
            get {
                return ResourceManager.GetString("IssueAdjustmentVoucher_AuthorizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By:.
        /// </summary>
        internal static string IssueAdjustmentVoucher_By {
            get {
                return ResourceManager.GetString("IssueAdjustmentVoucher_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Issued:.
        /// </summary>
        internal static string IssueAdjustmentVoucher_IssueDate {
            get {
                return ResourceManager.GetString("IssueAdjustmentVoucher_IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Adjustment Voucher.
        /// </summary>
        internal static string IssueAdjustmentVoucher_Title {
            get {
                return ResourceManager.GetString("IssueAdjustmentVoucher_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher#:.
        /// </summary>
        internal static string IssueAdjustmentVoucher_Voucher {
            get {
                return ResourceManager.GetString("IssueAdjustmentVoucher_Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string LogIn_Header {
            get {
                return ResourceManager.GetString("LogIn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string LogIn_PasswordLabel {
            get {
                return ResourceManager.GetString("LogIn_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string LogIn_SignIn_Button_Text {
            get {
                return ResourceManager.GetString("LogIn_SignIn_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name :.
        /// </summary>
        internal static string LogIn_UserNameLabel {
            get {
                return ResourceManager.GetString("LogIn_UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Collection Point.
        /// </summary>
        internal static string ManageCollectionPoint_GroupBox {
            get {
                return ResourceManager.GetString("ManageCollectionPoint_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select New Collection Point :.
        /// </summary>
        internal static string ManageCollectionPoint_SelectNewCollectionPoint {
            get {
                return ResourceManager.GetString("ManageCollectionPoint_SelectNewCollectionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Collection Point.
        /// </summary>
        internal static string ManageCollectionPoint_Title {
            get {
                return ResourceManager.GetString("ManageCollectionPoint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Copyright 2012-2013 Logic University. All Rights Reserved..
        /// </summary>
        internal static string MasterPageFooter_Text {
            get {
                return ResourceManager.GetString("MasterPageFooter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MasterPageHeader_Logout {
            get {
                return ResourceManager.GetString("MasterPageHeader_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss Time :.
        /// </summary>
        internal static string MissTime_Label {
            get {
                return ResourceManager.GetString("MissTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string PrintImage_text {
            get {
                return ResourceManager.GetString("PrintImage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date:.
        /// </summary>
        internal static string ReceiveOrderForm_DeliverDate {
            get {
                return ResourceManager.GetString("ReceiveOrderForm_DeliverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver Order No:.
        /// </summary>
        internal static string ReceiveOrderForm_DeliveryOrderNo {
            get {
                return ResourceManager.GetString("ReceiveOrderForm_DeliveryOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks(Clerk):   .
        /// </summary>
        internal static string ReceiveOrderForm_Remarks {
            get {
                return ResourceManager.GetString("ReceiveOrderForm_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name:.
        /// </summary>
        internal static string ReceiveOrderForm_SupplierName {
            get {
                return ResourceManager.GetString("ReceiveOrderForm_SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Order Form.
        /// </summary>
        internal static string ReceiveOrderForm_Title {
            get {
                return ResourceManager.GetString("ReceiveOrderForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ref PO Number:.
        /// </summary>
        internal static string ReceiveOrderForm_YourRefPONo {
            get {
                return ResourceManager.GetString("ReceiveOrderForm_YourRefPONo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove_Button_text {
            get {
                return ResourceManager.GetString("Remove_Button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept. Code :.
        /// </summary>
        internal static string RequestStationery_DeptCode_Label {
            get {
                return ResourceManager.GetString("RequestStationery_DeptCode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept. Name :.
        /// </summary>
        internal static string RequestStationery_DeptName_Label {
            get {
                return ResourceManager.GetString("RequestStationery_DeptName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Email :.
        /// </summary>
        internal static string RequestStationery_EmpEmail_Label {
            get {
                return ResourceManager.GetString("RequestStationery_EmpEmail_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name :.
        /// </summary>
        internal static string RequestStationery_EmpName_Label {
            get {
                return ResourceManager.GetString("RequestStationery_EmpName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number :.
        /// </summary>
        internal static string RequestStationery_EmpNumber_Label {
            get {
                return ResourceManager.GetString("RequestStationery_EmpNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Stationery.
        /// </summary>
        internal static string RequestStationery_Header {
            get {
                return ResourceManager.GetString("RequestStationery_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string Request_Button_text {
            get {
                return ResourceManager.GetString("Request_Button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept Code :.
        /// </summary>
        internal static string RequisitionDetails_DeptCode {
            get {
                return ResourceManager.GetString("RequisitionDetails_DeptCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept Name :.
        /// </summary>
        internal static string RequisitionDetails_DeptName {
            get {
                return ResourceManager.GetString("RequisitionDetails_DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Email Address :.
        /// </summary>
        internal static string RequisitionDetails_EmployeeEmailAddress {
            get {
                return ResourceManager.GetString("RequisitionDetails_EmployeeEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name :.
        /// </summary>
        internal static string RequisitionDetails_EmployeeName {
            get {
                return ResourceManager.GetString("RequisitionDetails_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number :.
        /// </summary>
        internal static string RequisitionDetails_EmployeeNumber {
            get {
                return ResourceManager.GetString("RequisitionDetails_EmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Stationery Details.
        /// </summary>
        internal static string RequisitionDetails_Label_Text {
            get {
                return ResourceManager.GetString("RequisitionDetails_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition Date :.
        /// </summary>
        internal static string RequisitionDetails_RequisitionDates {
            get {
                return ResourceManager.GetString("RequisitionDetails_RequisitionDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition ID :.
        /// </summary>
        internal static string RequisitionDetails_RequisitionID {
            get {
                return ResourceManager.GetString("RequisitionDetails_RequisitionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition Details.
        /// </summary>
        internal static string RequisitionDetails_Title {
            get {
                return ResourceManager.GetString("RequisitionDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset_Button_text {
            get {
                return ResourceManager.GetString("Reset_Button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        internal static string SearchResult_Label {
            get {
                return ResourceManager.GetString("SearchResult_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection ID:.
        /// </summary>
        internal static string SubmitRequisitionsToStore_CollectionID {
            get {
                return ResourceManager.GetString("SubmitRequisitionsToStore_CollectionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Point:.
        /// </summary>
        internal static string SubmitRequisitionsToStore_CollectionPoint {
            get {
                return ResourceManager.GetString("SubmitRequisitionsToStore_CollectionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit To Store.
        /// </summary>
        internal static string SubmitRequisitionsToStore_SubmitToStore {
            get {
                return ResourceManager.GetString("SubmitRequisitionsToStore_SubmitToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Requisitions To Store.
        /// </summary>
        internal static string SubmitRequisitionsToStore_Title {
            get {
                return ResourceManager.GetString("SubmitRequisitionsToStore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter or Select Collection Point.
        /// </summary>
        internal static string Text_CollectionPoint {
            get {
                return ResourceManager.GetString("Text_CollectionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email Address.
        /// </summary>
        internal static string Text_email {
            get {
                return ResourceManager.GetString("Text_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Employee Name.
        /// </summary>
        internal static string Text_EmployeeName {
            get {
                return ResourceManager.GetString("Text_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        internal static string Text_grouptext {
            get {
                return ResourceManager.GetString("Text_grouptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Item Description.
        /// </summary>
        internal static string Text_Item {
            get {
                return ResourceManager.GetString("Text_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        internal static string Text_new {
            get {
                return ResourceManager.GetString("Text_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Old Password.
        /// </summary>
        internal static string Text_old {
            get {
                return ResourceManager.GetString("Text_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Remarks.
        /// </summary>
        internal static string Text_Remarks {
            get {
                return ResourceManager.GetString("Text_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Requisition ID.
        /// </summary>
        internal static string Text_RequisitionID {
            get {
                return ResourceManager.GetString("Text_RequisitionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Actual Quantity.
        /// </summary>
        internal static string UpdateCollectionByItems_GridViewTitle {
            get {
                return ResourceManager.GetString("UpdateCollectionByItems_GridViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Details.
        /// </summary>
        internal static string UpdateCollectionByItems_GroupBoxTitle1 {
            get {
                return ResourceManager.GetString("UpdateCollectionByItems_GroupBoxTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Collection By Items.
        /// </summary>
        internal static string UpdateCollectionByItems_Header {
            get {
                return ResourceManager.GetString("UpdateCollectionByItems_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Date/Time :.
        /// </summary>
        internal static string UpdateCollectionByRequisions_CollectionDateTimeLabel {
            get {
                return ResourceManager.GetString("UpdateCollectionByRequisions_CollectionDateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection ID :.
        /// </summary>
        internal static string UpdateCollectionByRequisions_CollectionIDLabel {
            get {
                return ResourceManager.GetString("UpdateCollectionByRequisions_CollectionIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Point :.
        /// </summary>
        internal static string UpdateCollectionByRequisions_CollectionPointLabel {
            get {
                return ResourceManager.GetString("UpdateCollectionByRequisions_CollectionPointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection List.
        /// </summary>
        internal static string UpdateCollectionByRequisions_GroupBoxTitle {
            get {
                return ResourceManager.GetString("UpdateCollectionByRequisions_GroupBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition Details.
        /// </summary>
        internal static string UpdateCollectionByRequisions_GroupBoxTitle1 {
            get {
                return ResourceManager.GetString("UpdateCollectionByRequisions_GroupBoxTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition List for Selected Collection.
        /// </summary>
        internal static string UpdateCollectionByRequisions_RequisitionLabel {
            get {
                return ResourceManager.GetString("UpdateCollectionByRequisions_RequisitionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Collection .
        /// </summary>
        internal static string UpdateCollectionByRequisions_SelectCollectionLabel {
            get {
                return ResourceManager.GetString("UpdateCollectionByRequisions_SelectCollectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Collection By Requisitions.
        /// </summary>
        internal static string UpdateCollectionByRequisitions {
            get {
                return ResourceManager.GetString("UpdateCollectionByRequisitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Collected.
        /// </summary>
        internal static string UpdateStationeryRetrieval_Header_ButtonText {
            get {
                return ResourceManager.GetString("UpdateStationeryRetrieval_Header_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationery Retrieval List Details.
        /// </summary>
        internal static string UpdateStationeryRetrieval_Header_GroupBoxTitle {
            get {
                return ResourceManager.GetString("UpdateStationeryRetrieval_Header_GroupBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk Remarks :.
        /// </summary>
        internal static string UpdateStationeryRetrieval_Header_RemarksTitle {
            get {
                return ResourceManager.GetString("UpdateStationeryRetrieval_Header_RemarksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Stationery Retrieval.
        /// </summary>
        internal static string UpdateStationeryRetrieval_Header_Title {
            get {
                return ResourceManager.GetString("UpdateStationeryRetrieval_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized By:.
        /// </summary>
        internal static string ViewAdjustmentVoucherList_AuthorizedBy {
            get {
                return ResourceManager.GetString("ViewAdjustmentVoucherList_AuthorizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By:.
        /// </summary>
        internal static string ViewAdjustmentVoucherList_By {
            get {
                return ResourceManager.GetString("ViewAdjustmentVoucherList_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Issued:.
        /// </summary>
        internal static string ViewAdjustmentVoucherList_DateIssue {
            get {
                return ResourceManager.GetString("ViewAdjustmentVoucherList_DateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Adjustment Voucher List.
        /// </summary>
        internal static string ViewAdjustmentVoucherList_Title {
            get {
                return ResourceManager.GetString("ViewAdjustmentVoucherList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher#:.
        /// </summary>
        internal static string ViewAdjustmentVoucherList_Voucher {
            get {
                return ResourceManager.GetString("ViewAdjustmentVoucherList_Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description :.
        /// </summary>
        internal static string ViewStationeryCatalogue_EnterItemDescriptionLabel {
            get {
                return ResourceManager.GetString("ViewStationeryCatalogue_EnterItemDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Stationery Catalogue.
        /// </summary>
        internal static string ViewStationeryCatalogue_Header {
            get {
                return ResourceManager.GetString("ViewStationeryCatalogue_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationery List.
        /// </summary>
        internal static string ViewStationeryCatalogue_Label {
            get {
                return ResourceManager.GetString("ViewStationeryCatalogue_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Stationery Retrieval List.
        /// </summary>
        internal static string ViewStationeryRetrievalList_Title {
            get {
                return ResourceManager.GetString("ViewStationeryRetrievalList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Supplier.
        /// </summary>
        internal static string ViewStockCard_1stSupplier {
            get {
                return ResourceManager.GetString("ViewStockCard_1stSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Supplier.
        /// </summary>
        internal static string ViewStockCard_2ndSupplier {
            get {
                return ResourceManager.GetString("ViewStockCard_2ndSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Supplier.
        /// </summary>
        internal static string ViewStockCard_3rdSupplier {
            get {
                return ResourceManager.GetString("ViewStockCard_3rdSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin#:.
        /// </summary>
        internal static string ViewStockCard_Bin {
            get {
                return ResourceManager.GetString("ViewStockCard_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description:.
        /// </summary>
        internal static string ViewStockCard_ItemDescription {
            get {
                return ResourceManager.GetString("ViewStockCard_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No:.
        /// </summary>
        internal static string ViewStockCard_ItemNo {
            get {
                return ResourceManager.GetString("ViewStockCard_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier List:.
        /// </summary>
        internal static string ViewStockCard_SupplierList {
            get {
                return ResourceManager.GetString("ViewStockCard_SupplierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Stock Card.
        /// </summary>
        internal static string ViewStockCard_Title {
            get {
                return ResourceManager.GetString("ViewStockCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM:.
        /// </summary>
        internal static string ViewStockCard_UOM {
            get {
                return ResourceManager.GetString("ViewStockCard_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Supplier List.
        /// </summary>
        internal static string ViewSupplierList_Title {
            get {
                return ResourceManager.GetString("ViewSupplierList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        internal static string Withdraw_Button_text {
            get {
                return ResourceManager.GetString("Withdraw_Button_text", resourceCulture);
            }
        }
    }
}
